org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.249
loader_version_range=[4,)

mod_id=chocobosreborn
mod_name=Chocobos Reborn
mod_license=MIT
mod_group_id=tk.darrow.chocobosreborn
mod_version=1.0.11
mod_authors=Ahmi Darrow
mod_description=Final Fantasy VII chocobos in Minecraft: the farm line, greens and nuts, Chocobo Square racing. Original birds, original wark.
